services:
  - type: web
    name: thunder-booking
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Thunder Booking
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_TIMEZONE
        value: Asia/Thimphu
      - key: APP_URL
        value: https://thunderbooking.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: thunder-booking-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: errorlog
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

databases:
  - name: thunder-booking-db
    databaseName: thunder_booking
    user: thunder_booking_user
